### ISSUE TITLE
syp_ucs.csvファイルについて

### ISSUE THREAD

**Issue by toyjack** [shikeda/HDIC#10]
皆さま、こんにちは。
レポジトリのなかに、[SYP.txt](https://github.com/shikeda/HDIC/blob/master/SYP.txt)・[SongbenYupian.txt](https://github.com/shikeda/HDIC/blob/master/SongbenYupian.txt)・[syp_ucs.txt](https://github.com/shikeda/HDIC/blob/master/syp_ucs.csv)三つのファイルがありますが。
内容を見ると、`Version`のところはそれぞれ`1.0.6`、`1.0.4`、`1.0.2`と違います。
さらに分かり易くするには、この三つのファイルを統一化あるいは不要なファイルを削除したほうがよろしいでしょうか。

**Comment by shikeda** [comment]
ご指摘有難うございます。早速削除してみました。
