### ISSUE TITLE
An extra space should be removed

### ISSUE THREAD

**Issue by kzhr** [shikeda/HDIC#14]
In the following line,

> 1_092_B12	v4#49	目	矏	Regular		⿰⿱ 目白出分。莫緣反。點也、蜜也。	a042a011		双隷(17)。呂按「此處衍「矏」字。「蜜」似當作「密」，《爾雅釋言》：「矏，密也」。」

the TB_def column includes an extra space between IDS operators and the description, that is '⿰⿱* *目白出分'. Please consider its removal.

**Comment by shikeda** [comment]
Thank you.
ありがとうございます。修正しました。引き続きお気づきの点ご教示お願いします。

**Comment by toyjack** [comment]
[commit](https://github.com/shikeda/HDIC/commit/20bded76710b8d7c12b38184fb720211babc64c1)によって修正したので、本issueを閉じます。
