### ISSUE TITLE
新撰字鏡 (天治本): パブリックドメインソースの報告

### ISSUE THREAD

**Issue by a4lg** [shikeda/HDIC#16]
(GitHub の Issue はこの手の報告をするのにベストな場所とはいえませんが、) 参考情報として、天治本新撰字鏡において対照表を作るのに適しているとみられる新撰字鏡 (天治本) の六合館による影印本 (イリノイ大学蔵本) の存在についてお伝えしておきます。

https://archive.org/details/shinsenjikyotenj078800

**Comment by shikeda** [comment]
ありますね。確認しました。以前は国会図書館にも出てた時期がりましたが、今は制限されてるみたいで助かります。

**Comment by a4lg** [comment]
関連する方々の少なくとも 3 人に (Twitter 経由含む) 話が伝わったようですので、一旦 close します。
