### ISSUE TITLE
宋本玉篇の画像への参照情報を含めていただくことは可能でしょうか？

### ISSUE THREAD

**Issue by mpsuzuki** [shikeda/HDIC#34]
KTB_ndl.txtを参考にして、斯道文庫が公開している宮内庁宋本玉篇のIIIF画像の、
IIIFプロトコルを通じて特定のページを参照するための情報のTSVファイルを作って
みました。

https://github.com/mpsuzuki/pr-hdic/blob/pr-syp-keio-tsv/SYP_keio.tsv

manifest.jsonを通じてIIIFビューワで閲覧する限りは、斯道文庫が示す[画像の利用許諾](https://db2.sido.keio.ac.jp/kanseki/rights): 

> 「宮内庁書陵部収蔵漢籍集覧―書誌書影・全文影像データベース―」（以下、本データベースとします）に掲載する宮内庁書陵部図書寮文庫所蔵資料の画像は、利用者ご自身でダウンロードしていただけます。ただし、ダウンロードした画像を営利・非営利を問わず二次利用（画像のウェブサイトや刊行物への掲載，放映，翻刻等）する際には，宮内庁書陵部図書寮文庫への申請が必要です。利用申請の頁は[こちら](https://www.kunaicho.go.jp/kunaicho/shinsei/toshoryo.html)です。

に適合していると思いますが、パブリックドメインでない画像に関する情報は、
HDICへの取り込み可能性はあるでしょうか？パブリックドメインな澤存堂文庫の
画像で作ったほうが良いでしょうか？

**Comment by shikeda** [comment]
ご教示ありがとうございました。HDICへの取り込み可能性はちょっとイメージしにくいですが、ご希望のようにすすめていただいたかまいません。よろしくおねがいします。

**Comment by shikeda** [comment]
私の方で作業が必要でしたら、ご指示願います。

**Comment by mpsuzuki** [comment]
さっそくにありがとうございます、
ご確認いただきたいのはライセンスや著作権表示です。

https://github.com/mpsuzuki/pr-hdic/blob/d9f5c6838b3baf7912a99679e7d0bfb63dc52102/SYP_keio.tsv#L1C1-L48C2

基本的にはSYP.tsv, KTB_ndl.txtを参考に書いているのですが、

- 著作権者、連絡先、ライセンス(CC-SA 4.0)は他のHDICのファイルとおなじとしました
- データ加工について僕と守岡先生の名前の行を加えさせていただきました
- TSVカラム説明のあとに、各カラムのデータの正規表現の説明行を加えさせていただきました
- 科研助成の行に現在僕と守岡先生が受けている課題番号を1つ加えさせていただきました

という具合です。問題が無いかご確認いただければ幸いです。

KTB_ndl.txtが想定していたユースケースがございましたら、
そちらにも使えるよう調整したいと思います。
よろしくお願い致します。

**Comment by shikeda** [comment]
ライセンスを確認しました。問題ありません。よろしくおねがいします。

**Comment by shikeda** [comment]
鈴木様
ライセンスを確認しました。問題ありません。よろしくおねがいします。池田
---
池田証寿（IKEDA Shoju）


2024年5月8日(水) 20:33 mpsuzuki ***@***.***>:

**Comment by mpsuzuki** [comment]
Pull Requestを出しましたので、こちら一旦クローズとさせてください。
ありがとうございました。
